# Generated by Django 5.2.11 on 2026-02-23 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('artist_name', models.CharField(max_length=500)),
                ('album_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('preview_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('external_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrackEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('top_short', 'Top Tracks - Short Term'), ('top_medium', 'Top Tracks - Medium Term'), ('top_long', 'Top Tracks - Long Term'), ('recent', 'Recently Played')], max_length=20)),
                ('source_rank', models.IntegerField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_sync.spotifytrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['track'], name='spotify_syn_track_i_2579c5_idx'), models.Index(fields=['user'], name='spotify_syn_user_id_4760a3_idx'), models.Index(fields=['user', 'source_type'], name='spotify_syn_user_id_5c064c_idx')],
                'unique_together': {('user', 'track', 'source_type')},
            },
        ),
    ]
