# Generated by Django 5.2.11 on 2026-02-24 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, unique=True)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('starting', 'Starting'), ('in_game', 'In Game'), ('finished', 'Finished'), ('closed', 'Closed')], default='lobby', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('min_players', models.IntegerField(default=2)),
                ('max_players', models.IntegerField(default=8)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('is_host', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('connection_state', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='connected', max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='rooms_room_status_19affd_idx'),
        ),
        migrations.AddIndex(
            model_name='roomplayer',
            index=models.Index(fields=['room', 'connection_state'], name='rooms_roomp_room_id_b02cf7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomplayer',
            unique_together={('room', 'user')},
        ),
    ]
